create table image
(
    id  int primary key generated by default as identity,
    uri varchar unique
    person_id int unique references person(id)
)

create table person
(
    id       int primary key generated by default as identity,
    username varchar not null,
    password varchar not null,
    email    varchar not null
)